#!/bin/bash
set -euo pipefail

BINARY_NAME="${1:-}"
PROCESSING_TIME="${2:-}"
OBFUSCATED_COUNT="${3:-}"

if [ -z "$BINARY_NAME" ]; then
    echo "Error: Binary name is required"
    exit 1
fi

if [ ! "$(ls -A binaries/$BINARY_NAME/ 2>/dev/null)" ]; then
    echo "No benchmark results to commit"
    exit 0
fi

BRANCH_NAME="benchmark-results/$BINARY_NAME-$(date +%s)"

git config --local user.email "action@github.com"
git config --local user.name "GitHub Action"

git checkout -b "$BRANCH_NAME"

git add binaries/$BINARY_NAME/

if git diff --staged --quiet; then
    echo "No changes to commit"
    exit 0
fi

git commit -m "Add benchmark results for $BINARY_NAME

- Processing time: ${PROCESSING_TIME}s
- Obfuscated binaries: $OBFUSCATED_COUNT

Generated by automated benchmarking workflow"

git push origin "$BRANCH_NAME"

PR_BODY=$(cat << EOF
**Workflow run**: [${GITHUB_RUN_ID:-}](${GITHUB_SERVER_URL:-}/${GITHUB_REPOSITORY:-}/actions/runs/${GITHUB_RUN_ID:-})
EOF
)

gh pr create \
    --title "Benchmark results for $BINARY_NAME" \
    --body "$PR_BODY" \
    --label "automated" \
    --label "benchmark" \

echo "Successfully created PR for $BINARY_NAME on branch $BRANCH_NAME"